### ISSUE TITLE
Find another way to test if the calculation of the time difference is working ok

### ISSUE THREAD

**Issue by mbrandau** [mbrandau/timings#1]
Currently the test sets a timeout for 20ms and checks if the duration, the tracker returned, is between 19ms and 21ms. Probably not the best solution since tests sometimes fail because the test containers seem to not be fast enough.
One way of solving this problem would be to just make the threshold more tolerant, but there must be a better may to go.

**Comment by nab911** [comment]
Ill take a crack at this for hacktoberfest!
